// Generated by Framer (3bd990b)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["U543eEOLW", "tJrmyz9FV", "txFgeW4EE"];
const serializationHash = "framer-FqwEu";
const variantClassNames = {
    tJrmyz9FV: "framer-v-1ijgijq",
    txFgeW4EE: "framer-v-kjbxou",
    U543eEOLW: "framer-v-175wcop"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const rEqxinV9x = undefined;
const KhId2_Z78 = undefined;
const SwyWMQuoO = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "U543eEOLW",
    Phone: "txFgeW4EE",
    Tablet: "tJrmyz9FV"
};
const getProps = ({
    blessingOf,
    grandparents,
    height,
    id,
    parents,
    width,
    ...props
}) => {
    return { ...props,
        KhId2_Z78: grandparents ? ? props.KhId2_Z78 ? ? "Smt. Lata Devi & Sm. Kamal Kapoor",
        rEqxinV9x: blessingOf ? ? props.rEqxinV9x ? ? "With the heavenly blessings of ",
        SwyWMQuoO: parents ? ? props.SwyWMQuoO ? ? "Mrs. Reena & Mr. Rajiv Kapoor",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "U543eEOLW"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        rEqxinV9x,
        KhId2_Z78,
        SwyWMQuoO,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "U543eEOLW",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-175wcop", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "U543eEOLW",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        tJrmyz9FV: {
                            "data-framer-name": "Tablet"
                        },
                        txFgeW4EE: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "100%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "With the heavenly blessings of "
                            })
                        }),
                        className: "framer-3xglzy",
                        "data-framer-name": "With the heavenly blessings of Smt. Sita Devi & Sm. Om Puri",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "j08IdWU8h",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: rEqxinV9x,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            txFgeW4EE: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.03em",
                                            "--framer-line-height": "100%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "With the heavenly blessings of "
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "100%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "Smt. Sita Devi & Sm. Kamal Mittal"
                            })
                        }),
                        className: "framer-19djrwi",
                        "data-framer-name": "With the heavenly blessings of Smt. Sita Devi & Sm. Om Puri",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "UBBIa8KLO",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: KhId2_Z78,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            txFgeW4EE: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.03em",
                                            "--framer-line-height": "100%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "Smt. Sita Devi & Sm. Kamal Mittal"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "——"
                            })
                        }),
                        className: "framer-1k1fru6",
                        "data-framer-name": "and",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "f6mRsMFTJ",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            txFgeW4EE: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.03em",
                                            "--framer-line-height": "150%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "——"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.03em",
                                    "--framer-line-height": "150%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "Mrs. Lata & Mr. Kishore Kapoor"
                            })
                        }),
                        className: "framer-ximwwv",
                        "data-framer-name": "Mrs. Lata & Mr. Kishore Kapoor",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "kmW_PLUr_",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: SwyWMQuoO,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            txFgeW4EE: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.03em",
                                            "--framer-line-height": "150%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "Mrs. Lata & Mr. Kishore Kapoor"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-FqwEu.framer-x5p239, .framer-FqwEu .framer-x5p239 { display: block; }", ".framer-FqwEu.framer-175wcop { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 38px 0px 38px 0px; position: relative; width: 1200px; }", ".framer-FqwEu .framer-3xglzy, .framer-FqwEu .framer-19djrwi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-FqwEu .framer-1k1fru6, .framer-FqwEu .framer-ximwwv { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-FqwEu.framer-v-1ijgijq.framer-175wcop { padding: 38px 180px 38px 180px; }", ".framer-FqwEu.framer-v-kjbxou.framer-175wcop { padding: 38px 40px 38px 40px; width: 462px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 256
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"tJrmyz9FV":{"layout":["fixed","auto"]},"txFgeW4EE":{"layout":["fixed","auto"]}}}
 * @framerVariables {"rEqxinV9x":"blessingOf","KhId2_Z78":"grandparents","SwyWMQuoO":"parents"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerXr_Hx494q = withCSS(Component, css, "framer-FqwEu");
export default FramerXr_Hx494q;
FramerXr_Hx494q.displayName = "Groom's family names";
FramerXr_Hx494q.defaultProps = {
    height: 256,
    width: 1200
};
addPropertyControls(FramerXr_Hx494q, {
    variant: {
        options: ["U543eEOLW", "tJrmyz9FV", "txFgeW4EE"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    rEqxinV9x: {
        defaultValue: "With the heavenly blessings of ",
        displayTextArea: true,
        title: "Blessing of",
        type: ControlType.String
    },
    KhId2_Z78: {
        defaultValue: "Smt. Lata Devi & Sm. Kamal Kapoor",
        description: "Enter your grandparent's name above",
        displayTextArea: true,
        title: "Grandparents",
        type: ControlType.String
    },
    SwyWMQuoO: {
        defaultValue: "Mrs. Reena & Mr. Rajiv Kapoor",
        description: "Enter your parent's name above\n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Parents",
        type: ControlType.String
    }
});
addFonts(FramerXr_Hx494q, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Cormorant Upright",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant Upright",
        url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerXr_Hx494q",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"rEqxinV9x\":\"blessingOf\",\"KhId2_Z78\":\"grandparents\",\"SwyWMQuoO\":\"parents\"}",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"tJrmyz9FV\":{\"layout\":[\"fixed\",\"auto\"]},\"txFgeW4EE\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "1200",
                "framerIntrinsicHeight": "256",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./Xr_Hx494q.map