// Generated by Framer (9805f18)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["Y6unreR3_", "p1zFxwbGv", "uByGehVIJ"];
const serializationHash = "framer-aXrkt";
const variantClassNames = {
    p1zFxwbGv: "framer-v-u1swbt",
    uByGehVIJ: "framer-v-1beffmi",
    Y6unreR3_: "framer-v-1p3qhwc"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "Y6unreR3_",
    Phone: "uByGehVIJ",
    Tablet: "p1zFxwbGv"
};
const getProps = ({
    height,
    id,
    name1,
    name2,
    width,
    ...props
}) => {
    return { ...props,
        dJVbfF52C: name2 ? ? props.dJVbfF52C ? ? "Kanika",
        tml4boL7l: name1 ? ? props.tml4boL7l ? ? "Abhishek",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "Y6unreR3_"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        tml4boL7l,
        dJVbfF52C,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "Y6unreR3_",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1p3qhwc", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "Y6unreR3_",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        p1zFxwbGv: {
                            "data-framer-name": "Tablet"
                        },
                        uByGehVIJ: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "150px",
                                    "--framer-line-height": "190.1%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "Abhishek"
                            })
                        }),
                        className: "framer-11ag0sw",
                        "data-framer-name": "Aaditya",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "cYGbsEkt6",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: tml4boL7l,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            uByGehVIJ: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "70px",
                                            "--framer-line-height": "190.1%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "Abhishek"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "156px",
                                    "--framer-line-height": "110%",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "&"
                            })
                        }),
                        className: "framer-rtadh1",
                        "data-framer-name": "&",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "jkKJDlfk4",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            uByGehVIJ: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "70px",
                                            "--framer-line-height": "110%",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "&"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                    "--framer-font-family": '"Cormorant", "Cormorant Placeholder", serif',
                                    "--framer-font-size": "150px",
                                    "--framer-line-height": "60.1%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "Kanika"
                            })
                        }),
                        className: "framer-13k4cyv",
                        "data-framer-name": "Veera",
                        fonts: ["GF;Cormorant-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "PBLQbVR8j",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: dJVbfF52C,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            uByGehVIJ: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                            "--framer-font-family": '"Cormorant", "Cormorant Placeholder", serif',
                                            "--framer-font-size": "70px",
                                            "--framer-line-height": "60.1%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "Kanika"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-aXrkt.framer-u1iaiu, .framer-aXrkt .framer-u1iaiu { display: block; }", ".framer-aXrkt.framer-1p3qhwc { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }", ".framer-aXrkt .framer-11ag0sw { flex: none; height: 210px; position: relative; white-space: pre; width: auto; }", ".framer-aXrkt .framer-rtadh1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-aXrkt .framer-13k4cyv { flex: none; height: 186px; position: relative; white-space: pre; width: auto; }", ".framer-aXrkt.framer-v-1beffmi.framer-1p3qhwc { width: min-content; }", ".framer-aXrkt.framer-v-1beffmi .framer-11ag0sw { height: 104px; }", ".framer-aXrkt.framer-v-1beffmi .framer-13k4cyv { height: 76px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 567.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"p1zFxwbGv":{"layout":["fixed","auto"]},"uByGehVIJ":{"layout":["auto","auto"]}}}
 * @framerVariables {"tml4boL7l":"name1","dJVbfF52C":"name2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerzy6YBh8Kk = withCSS(Component, css, "framer-aXrkt");
export default Framerzy6YBh8Kk;
Framerzy6YBh8Kk.displayName = "Bride & Groom";
Framerzy6YBh8Kk.defaultProps = {
    height: 567.5,
    width: 1200
};
addPropertyControls(Framerzy6YBh8Kk, {
    variant: {
        options: ["Y6unreR3_", "p1zFxwbGv", "uByGehVIJ"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    tml4boL7l: {
        defaultValue: "Abhishek",
        description: "Enter Groom's name above\n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Name 1",
        type: ControlType.String
    },
    dJVbfF52C: {
        defaultValue: "Kanika",
        description: "Enter bride's name above\n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Name 2",
        type: ControlType.String
    }
});
addFonts(Framerzy6YBh8Kk, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Cormorant Upright",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant Upright",
        url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Cormorant",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant",
        url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerzy6YBh8Kk",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"p1zFxwbGv\":{\"layout\":[\"fixed\",\"auto\"]},\"uByGehVIJ\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "1200",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerVariables": "{\"tml4boL7l\":\"name1\",\"dJVbfF52C\":\"name2\"}",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "567.5"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zy6YBh8Kk.map