// Generated by Framer (336f227)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["sOk3qbz4s", "jOLXNds8a", "BOfIK4rF3"];
const serializationHash = "framer-Zfszz";
const variantClassNames = {
    BOfIK4rF3: "framer-v-3wkc1y",
    jOLXNds8a: "framer-v-l1x47p",
    sOk3qbz4s: "framer-v-1v45h18"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "sOk3qbz4s",
    Phone: "BOfIK4rF3",
    Tablet: "jOLXNds8a"
};
const getProps = ({
    height,
    id,
    message,
    width,
    ...props
}) => {
    return { ...props,
        UIYLQtWu6: message ? ? props.UIYLQtWu6 ? ? "Mittal family is excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. ",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "sOk3qbz4s"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        UIYLQtWu6,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "sOk3qbz4s",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1v45h18", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "sOk3qbz4s",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        BOfIK4rF3: {
                            "data-framer-name": "Phone"
                        },
                        jOLXNds8a: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1y7r59s",
                        layoutDependency: layoutDependency,
                        layoutId: "xTm5y9skX",
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                        "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                        "--framer-font-size": "14px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(231, 147, 0))"
                                    },
                                    children: "Mittal family is excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. "
                                })
                            }),
                            className: "framer-9dn961",
                            "data-framer-name": "Our families are excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives.",
                            fonts: ["GF;Cormorant Upright-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "qIQSeBIE4",
                            style: {
                                "--extracted-r6o4lv": "rgb(231, 147, 0)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: UIYLQtWu6,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Zfszz.framer-4ianta, .framer-Zfszz .framer-4ianta { display: block; }", ".framer-Zfszz.framer-1v45h18 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 418px; }", ".framer-Zfszz .framer-1y7r59s { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-Zfszz .framer-9dn961 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 33.5
 * @framerIntrinsicWidth 418
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"jOLXNds8a":{"layout":["fixed","auto"]},"BOfIK4rF3":{"layout":["fixed","auto"]}}}
 * @framerVariables {"UIYLQtWu6":"message"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerXAS76Wlzw = withCSS(Component, css, "framer-Zfszz");
export default FramerXAS76Wlzw;
FramerXAS76Wlzw.displayName = "Family message";
FramerXAS76Wlzw.defaultProps = {
    height: 33.5,
    width: 418
};
addPropertyControls(FramerXAS76Wlzw, {
    variant: {
        options: ["sOk3qbz4s", "jOLXNds8a", "BOfIK4rF3"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    UIYLQtWu6: {
        defaultValue: "Mittal family is excited that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. ",
        description: "Write a custom family message above\n\nFind more templates on missingpiecedesign.com",
        displayTextArea: true,
        title: "Message",
        type: ControlType.String
    }
});
addFonts(FramerXAS76Wlzw, [{
    explicitInter: true,
    fonts: [{
        family: "Cormorant Upright",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerXAS76Wlzw",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "33.5",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"jOLXNds8a\":{\"layout\":[\"fixed\",\"auto\"]},\"BOfIK4rF3\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "418",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"UIYLQtWu6\":\"message\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./XAS76Wlzw.map