// Generated by Framer (b71bad1)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const MotionDivWithFX = withFX(motion.div);
const serializationHash = "framer-yF5Cc";
const variantClassNames = {
    bc1LDyZKw: "framer-v-15br9zz"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: 1,
    type: "spring"
};
const animation1 = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const transition2 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "bc1LDyZKw",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition2,
                children: /*#__PURE__*/ _jsx(MotionDivWithFX, { ...restProps,
                    ...gestureHandlers,
                    __framer__animate: {
                        transition: transition1
                    },
                    __framer__animateOnce: false,
                    __framer__enter: animation,
                    __framer__exit: animation1,
                    __framer__styleAppearEffectEnabled: true,
                    __framer__threshold: 0,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: cx(scopingClassNames, "framer-15br9zz", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "bc1LDyZKw",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: 38.81,
                        borderBottomRightRadius: 38.81,
                        borderTopLeftRadius: 38.81,
                        borderTopRightRadius: 38.81,
                        ...style
                    },
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1y7vv0i",
                        layoutDependency: layoutDependency,
                        layoutId: "wW0c7mHJA",
                        children: /*#__PURE__*/ _jsx(Image, {
                            background: {
                                alt: "",
                                fit: "fill",
                                intrinsicHeight: 26.5,
                                intrinsicWidth: 153.5,
                                loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 48) - 0 - ((componentViewport ? .height || 48) - 0) * 1) / 2) + (0 + (((componentViewport ? .height || 48) - 0) * 1 - 0 - (((componentViewport ? .height || 48) - 0) * 1 - 0) * 1) / 2)),
                                pixelHeight: 1024,
                                pixelWidth: 1024,
                                sizes: `calc(${(((componentViewport?.height||48)-0)*1-0)*1} * 5.7925)`,
                                src: "https://framerusercontent.com/images/3vpFOuN5tHb2JuYqzoPGPaRcA.png?scale-down-to=512&width=1024&height=1024",
                                srcSet: "https://framerusercontent.com/images/3vpFOuN5tHb2JuYqzoPGPaRcA.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/3vpFOuN5tHb2JuYqzoPGPaRcA.png?width=1024&height=1024 1024w"
                            },
                            className: "framer-1ecq5nh",
                            "data-framer-name": "Missing Piece Logo",
                            layoutDependency: layoutDependency,
                            layoutId: "AvZ00yb6s"
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-yF5Cc.framer-txbcth, .framer-yF5Cc .framer-txbcth { display: block; }", ".framer-yF5Cc.framer-15br9zz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 48px; justify-content: center; overflow: visible; padding: 0px 5px 0px 0px; position: relative; width: 215px; }", ".framer-yF5Cc .framer-1y7vv0i { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-yF5Cc .framer-1ecq5nh { align-content: center; align-items: center; aspect-ratio: 5.7924528301886795 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; mix-blend-mode: exclusion; overflow: visible; padding: 0px; position: relative; width: var(--framer-aspect-ratio-supported, 278px); }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 48
 * @framerIntrinsicWidth 215
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerKHQgVYK_f = withCSS(Component, css, "framer-yF5Cc");
export default FramerKHQgVYK_f;
FramerKHQgVYK_f.displayName = "Watermark";
FramerKHQgVYK_f.defaultProps = {
    height: 48,
    width: 215
};
addFonts(FramerKHQgVYK_f, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerKHQgVYK_f",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "215",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "48",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./KHQgVYK_f.map