// Generated by Framer (4076eae)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import CTA2 from "https://framerusercontent.com/modules/CAYlJEtsdIJh39cSI95x/9npA7VwvCKleSurPfUCE/bMSELzOfJ.js";
const CTA2Fonts = getFonts(CTA2);
const serializationHash = "framer-m4q2y";
const variantClassNames = {
    bz3DndcPk: "framer-v-zhx63x"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "bz3DndcPk",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-zhx63x", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "bz3DndcPk",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 510,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 510) / 2 + 0 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-a4swwf-container",
                            layoutDependency: layoutDependency,
                            layoutId: "sB2B05pUP-container",
                            nodeId: "sB2B05pUP",
                            rendersWithMotion: true,
                            scopeId: "zqB219G43",
                            children: /*#__PURE__*/ _jsx(CTA2, {
                                height: "100%",
                                id: "sB2B05pUP",
                                layoutId: "sB2B05pUP",
                                style: {
                                    width: "100%"
                                },
                                variant: "kDcaosY36",
                                width: "100%"
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-m4q2y.framer-vy6rvh, .framer-m4q2y .framer-vy6rvh { display: block; }", ".framer-m4q2y.framer-zhx63x { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }", ".framer-m4q2y .framer-a4swwf-container { flex: none; height: auto; position: sticky; top: 50px; width: 100%; z-index: 1; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 510
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerzqB219G43 = withCSS(Component, css, "framer-m4q2y");
export default FramerzqB219G43;
FramerzqB219G43.displayName = "CTA - Instagram";
FramerzqB219G43.defaultProps = {
    height: 510,
    width: 1200
};
addFonts(FramerzqB219G43, [{
    explicitInter: true,
    fonts: []
}, ...CTA2Fonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerzqB219G43",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "1200",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "510",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}