// Generated by Framer (77d7dc9)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-cHKZ7 .framer-styles-preset-s3v1ib:not(.rich-text-wrapper), .framer-cHKZ7 .framer-styles-preset-s3v1ib.rich-text-wrapper a { --framer-link-text-color: #45a086; --framer-link-text-decoration: underline; }"];
export const className = "framer-cHKZ7";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}