// Generated by Framer (9805f18)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["wkFtyVQ7o", "xegNn3FSd", "L0bJxYHja"];
const serializationHash = "framer-nva0a";
const variantClassNames = {
    L0bJxYHja: "framer-v-1g85f57",
    wkFtyVQ7o: "framer-v-yerj29",
    xegNn3FSd: "framer-v-d83l8q"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "wkFtyVQ7o",
    Phone: "L0bJxYHja",
    Tablet: "xegNn3FSd"
};
const getProps = ({
    height,
    id,
    parents,
    relation,
    width,
    ...props
}) => {
    return { ...props,
        PF8ftF8Ur: parents ? ? props.PF8ftF8Ur ? ? "Mrs. Reena & Mr. Kamal Mittal,",
        sKFuJb5xa: relation ? ? props.sKFuJb5xa ? ? "Daughter of",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "wkFtyVQ7o"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        sKFuJb5xa,
        PF8ftF8Ur,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "wkFtyVQ7o",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-yerj29", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "wkFtyVQ7o",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        L0bJxYHja: {
                            "data-framer-name": "Phone"
                        },
                        xegNn3FSd: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-f11cs3",
                        layoutDependency: layoutDependency,
                        layoutId: "GYfE_iu8X",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                        "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                        "--framer-font-size": "30px",
                                        "--framer-letter-spacing": "-0.05em",
                                        "--framer-line-height": "100%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                    },
                                    children: "Daughter of"
                                })
                            }),
                            className: "framer-fsyar",
                            "data-framer-name": "You to join us in the wedding celebrations of",
                            fonts: ["GF;Cormorant Upright-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "qtpASeG2I",
                            style: {
                                "--extracted-r6o4lv": "rgb(243, 236, 186)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: sKFuJb5xa,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                L0bJxYHja: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                                "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                                "--framer-font-size": "20px",
                                                "--framer-letter-spacing": "-0.05em",
                                                "--framer-line-height": "100%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                            },
                                            children: "Daughter of"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                        "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                        "--framer-font-size": "30px",
                                        "--framer-letter-spacing": "-0.05em",
                                        "--framer-line-height": "100%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                    },
                                    children: "Mrs. Reena & Mr. Kamal Mittal,"
                                })
                            }),
                            className: "framer-10pnu1m",
                            "data-framer-name": "You to join us in the wedding celebrations of",
                            fonts: ["GF;Cormorant Upright-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "DbPxaT9Zn",
                            style: {
                                "--extracted-r6o4lv": "rgb(243, 236, 186)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: PF8ftF8Ur,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                L0bJxYHja: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                                "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                                "--framer-font-size": "20px",
                                                "--framer-letter-spacing": "-0.05em",
                                                "--framer-line-height": "100%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                            },
                                            children: "Mrs. Reena & Mr. Kamal Mittal,"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })]
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.05em",
                                    "--framer-line-height": "100%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "On the following events"
                            })
                        }),
                        className: "framer-12rhqe6",
                        "data-framer-name": "You to join us in the wedding celebrations of",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "seEwhnVZ8",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            L0bJxYHja: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.05em",
                                            "--framer-line-height": "100%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "On the following events"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-nva0a.framer-chhwvt, .framer-nva0a .framer-chhwvt { display: block; }", ".framer-nva0a.framer-yerj29 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 46px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 32px 0px 32px 0px; position: relative; width: 1200px; }", ".framer-nva0a .framer-f11cs3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 9px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-nva0a .framer-fsyar, .framer-nva0a .framer-10pnu1m, .framer-nva0a .framer-12rhqe6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 209
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"xegNn3FSd":{"layout":["fixed","auto"]},"L0bJxYHja":{"layout":["fixed","auto"]}}}
 * @framerVariables {"sKFuJb5xa":"relation","PF8ftF8Ur":"parents"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerATw0jP31y = withCSS(Component, css, "framer-nva0a");
export default FramerATw0jP31y;
FramerATw0jP31y.displayName = "Bride's family names";
FramerATw0jP31y.defaultProps = {
    height: 209,
    width: 1200
};
addPropertyControls(FramerATw0jP31y, {
    variant: {
        options: ["wkFtyVQ7o", "xegNn3FSd", "L0bJxYHja"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    sKFuJb5xa: {
        defaultValue: "Daughter of",
        description: '"Son of" or "Daughter of"',
        displayTextArea: false,
        title: "Relation",
        type: ControlType.String
    },
    PF8ftF8Ur: {
        defaultValue: "Mrs. Reena & Mr. Kamal Mittal,",
        description: "Enter parent's names above\n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Parents",
        type: ControlType.String
    }
});
addFonts(FramerATw0jP31y, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Cormorant Upright",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant Upright",
        url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerATw0jP31y",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"sKFuJb5xa\":\"relation\",\"PF8ftF8Ur\":\"parents\"}",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"xegNn3FSd\":{\"layout\":[\"fixed\",\"auto\"]},\"L0bJxYHja\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "1200",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "209",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ATw0jP31y.map