// Generated by Framer (3bd990b)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["FJ46gfTZ2", "MeE7LEOpP", "JbnpMq1o9"];
const serializationHash = "framer-cdl7V";
const variantClassNames = {
    FJ46gfTZ2: "framer-v-10bgcqa",
    JbnpMq1o9: "framer-v-1akj9wm",
    MeE7LEOpP: "framer-v-b8sbvs"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const i9HrUZDnv = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const transition2 = {
    delay: 0,
    duration: 1,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const animation = {
    opacity: 1,
    rotate: 360,
    rotateX: 0,
    rotateY: 0,
    scale: 1.1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Section 1": "FJ46gfTZ2",
    "Section 2": "MeE7LEOpP",
    "Section 3": "JbnpMq1o9"
};
const getProps = ({
    height,
    id,
    link,
    width,
    ...props
}) => {
    return { ...props,
        i9HrUZDnv: link ? ? props.i9HrUZDnv,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "FJ46gfTZ2"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        i9HrUZDnv,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "FJ46gfTZ2",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: i9HrUZDnv,
                    motionChild: true,
                    nodeId: "FJ46gfTZ2",
                    openInNewTab: true,
                    scopeId: "EZuXxhgL1",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-10bgcqa",className,classNames)} framer-19b645y`,
                        "data-framer-name": "Section 1",
                        layoutDependency: layoutDependency,
                        layoutId: "FJ46gfTZ2",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            JbnpMq1o9: {
                                "data-framer-name": "Section 3"
                            },
                            MeE7LEOpP: {
                                "data-framer-name": "Section 2"
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __framer__loop: animation,
                            __framer__loopEffectEnabled: true,
                            __framer__loopPauseOffscreen: false,
                            __framer__loopRepeatDelay: 0,
                            __framer__loopRepeatType: "mirror",
                            __framer__loopTransition: transition2,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            className: "framer-1vsrqv2",
                            "data-border": true,
                            "data-framer-name": "Ellipse 2",
                            layoutDependency: layoutDependency,
                            layoutId: "QK14OIIH6",
                            style: {
                                "--border-bottom-width": "2px",
                                "--border-color": "rgb(220, 221, 166)",
                                "--border-left-width": "2px",
                                "--border-right-width": "2px",
                                "--border-style": "solid",
                                "--border-top-width": "2px",
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%"
                            },
                            variants: {
                                JbnpMq1o9: {
                                    "--border-color": "rgb(105, 107, 54)"
                                },
                                MeE7LEOpP: {
                                    "--border-color": "rgb(251, 237, 226)"
                                }
                            }
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-stgyg9",
                            "data-border": true,
                            "data-framer-name": "Ellipse 1",
                            layoutDependency: layoutDependency,
                            layoutId: "UcF8Bg79o",
                            style: {
                                "--border-bottom-width": "9px",
                                "--border-color": "rgb(220, 221, 166)",
                                "--border-left-width": "9px",
                                "--border-right-width": "9px",
                                "--border-style": "solid",
                                "--border-top-width": "9px",
                                borderBottomLeftRadius: "100%",
                                borderBottomRightRadius: "100%",
                                borderTopLeftRadius: "100%",
                                borderTopRightRadius: "100%"
                            },
                            transformTemplate: transformTemplate1,
                            variants: {
                                JbnpMq1o9: {
                                    "--border-color": "rgb(105, 107, 54)"
                                },
                                MeE7LEOpP: {
                                    "--border-color": "rgb(251, 237, 226)"
                                }
                            }
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-cdl7V.framer-19b645y, .framer-cdl7V .framer-19b645y { display: block; }", ".framer-cdl7V.framer-10bgcqa { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 99px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 127px; }", ".framer-cdl7V .framer-1vsrqv2 { flex: none; height: 99px; left: calc(50.00000000000002% - 99px / 2); position: absolute; top: 0px; width: 99px; z-index: 1; }", ".framer-cdl7V .framer-stgyg9 { aspect-ratio: 1 / 1; bottom: 16px; flex: none; left: 50%; position: absolute; top: 17px; width: var(--framer-aspect-ratio-supported, 66px); z-index: 1; }", '.framer-cdl7V[data-border="true"]::after, .framer-cdl7V [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 99
 * @framerIntrinsicWidth 127
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MeE7LEOpP":{"layout":["fixed","fixed"]},"JbnpMq1o9":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"i9HrUZDnv":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerEZuXxhgL1 = withCSS(Component, css, "framer-cdl7V");
export default FramerEZuXxhgL1;
FramerEZuXxhgL1.displayName = "Button";
FramerEZuXxhgL1.defaultProps = {
    height: 99,
    width: 127
};
addPropertyControls(FramerEZuXxhgL1, {
    variant: {
        options: ["FJ46gfTZ2", "MeE7LEOpP", "JbnpMq1o9"],
        optionTitles: ["Section 1", "Section 2", "Section 3"],
        title: "Variant",
        type: ControlType.Enum
    },
    i9HrUZDnv: {
        description: "Find more templates on missingpieceinvites.com",
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerEZuXxhgL1, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerEZuXxhgL1",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerVariables": "{\"i9HrUZDnv\":\"link\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"MeE7LEOpP\":{\"layout\":[\"fixed\",\"fixed\"]},\"JbnpMq1o9\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "127",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "99"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./EZuXxhgL1.map