// Generated by Framer (72b52f5)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1y2hfxk",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "1ix6lmh",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "rw19y8",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            Bgubyx1ZN: "location-1",
            BwDWIGqJo: "instagram",
            BZJo6HYmH: "lantern",
            FGAz9OWDj: "lantern-4",
            nwTFmbP7D: "lantern-3",
            pCpJNQCTt: "location",
            pl0Y3CfKj: "lantern-2",
            s2nj141jB: "rsvp",
            Tjt66Z8da: "lantern-1",
            uoLP2atxb: "bride-and-groom",
            uRZvt4JO8: "invite",
            VJmOr_duf: "lantern-5",
            y1qExX2As: "things-to-know",
            zoBmUtJQj: "bride-and-groom-1"
        },
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-KP8HB",
        socialImage: "https://framerusercontent.com/assets/7LPUQldg1w5B1Zrz0pCfh0AeQw.png",
        title: "Meenaya – South Indian Wedding Invitation Website Template",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}