// Generated by Framer (4076eae)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["rfiMFH_Cu", "ajdNH6oKk"];
const serializationHash = "framer-n6tZe";
const variantClassNames = {
    ajdNH6oKk: "framer-v-n5lh7j",
    rfiMFH_Cu: "framer-v-12yuojt"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "rfiMFH_Cu",
    Phone: "ajdNH6oKk"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "rfiMFH_Cu"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "rfiMFH_Cu",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-12yuojt", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "rfiMFH_Cu",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        ajdNH6oKk: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ajbebj",
                        "data-framer-name": "CTA - 1",
                        layoutDependency: layoutDependency,
                        layoutId: "jYDI654zT",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsxs(React.Fragment, {
                                children: [ /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                        "--framer-font-family": '"Aboreto", sans-serif',
                                        "--framer-font-size": "70px",
                                        "--framer-line-height": "115.74%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                    },
                                    children: "Follow "
                                }), /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                        "--framer-font-family": '"Aboreto", sans-serif',
                                        "--framer-font-size": "70px",
                                        "--framer-line-height": "115.74%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-2gxw0f, rgb(105, 107, 54))"
                                    },
                                    children: "the action"
                                })]
                            }),
                            className: "framer-1lynk1q",
                            "data-framer-name": "join our journey",
                            fonts: ["GF;Aboreto-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "RL6nQdP5C",
                            style: {
                                "--extracted-2gxw0f": "rgb(105, 107, 54)",
                                "--extracted-r6o4lv": "rgb(105, 107, 54)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            variants: {
                                ajdNH6oKk: {
                                    "--extracted-1iakedh": "rgb(105, 107, 54)"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                ajdNH6oKk: {
                                    children: /*#__PURE__*/ _jsxs(React.Fragment, {
                                        children: [ /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                                "--framer-font-family": '"Aboreto", sans-serif',
                                                "--framer-font-size": "70px",
                                                "--framer-line-height": "115.74%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                            },
                                            children: "Follow "
                                        }), /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                                "--framer-font-family": '"Aboreto", sans-serif',
                                                "--framer-font-size": "70px",
                                                "--framer-line-height": "115.74%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-2gxw0f, rgb(105, 107, 54))"
                                            },
                                            children: "the "
                                        }), /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                                "--framer-font-family": '"Aboreto", sans-serif',
                                                "--framer-font-size": "70px",
                                                "--framer-line-height": "115.74%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-1iakedh, rgb(105, 107, 54))"
                                            },
                                            children: "action"
                                        })]
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                        "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                        "--framer-font-size": "20px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                    },
                                    children: "Click to open our Instagram page"
                                })
                            }),
                            className: "framer-1tv2weq",
                            "data-framer-name": "Click to open the map",
                            fonts: ["GF;Yaldevi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "hyjf1Y6od",
                            style: {
                                "--extracted-r6o4lv": "rgb(105, 107, 54)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-n6tZe.framer-1u0kru5, .framer-n6tZe .framer-1u0kru5 { display: block; }", ".framer-n6tZe.framer-12yuojt { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 100px 0px 100px; position: relative; width: min-content; }", ".framer-n6tZe .framer-ajbebj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 36px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 50px 0px 30px 0px; position: relative; width: 627px; }", ".framer-n6tZe .framer-1lynk1q { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-n6tZe .framer-1tv2weq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 479px; word-break: break-word; word-wrap: break-word; }", ".framer-n6tZe.framer-v-n5lh7j.framer-12yuojt { padding: 0px; }", ".framer-n6tZe.framer-v-n5lh7j .framer-ajbebj { padding: 10px 0px 30px 0px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 301
 * @framerIntrinsicWidth 827
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"ajdNH6oKk":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameruLaYJJx25 = withCSS(Component, css, "framer-n6tZe");
export default FrameruLaYJJx25;
FrameruLaYJJx25.displayName = "CTA - 3";
FrameruLaYJJx25.defaultProps = {
    height: 301,
    width: 827
};
addPropertyControls(FrameruLaYJJx25, {
    variant: {
        options: ["rfiMFH_Cu", "ajdNH6oKk"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FrameruLaYJJx25, [{
    explicitInter: true,
    fonts: [{
        family: "Aboreto",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/aboreto/v2/5DCXAKLhwDDQ4N8blKHeA2yuxSY.woff2",
        weight: "400"
    }, {
        family: "Yaldevi",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/yaldevi/v17/cY9afj6VW0NMrDWtDNzCOwlPMq9SLpdxJzvtbxLCBJkS.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameruLaYJJx25",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"ajdNH6oKk\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "827",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "301",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./uLaYJJx25.map