// Generated by Framer (f36d8c8)
export default function metadata(params, activeLocale) {
    return {
        description: "Create a beautiful wedding invite that opens as a website. Edit anytime and share instantly on WhatsApp. Modern, simple, and made for every ceremony.",
        favicon: "https://framerusercontent.com/assets/VRr5oPbK8EC2e8xlsQcVIsS47c.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/7LPUQldg1w5B1Zrz0pCfh0AeQw.png",
        title: "Wedding Invitation Templates – Missing Piece"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}