// Generated by Framer (9805f18)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["VM9yIq6SY", "CaaLAiDVm", "wnBX45izL"];
const serializationHash = "framer-aHoRy";
const variantClassNames = {
    CaaLAiDVm: "framer-v-10763hp",
    VM9yIq6SY: "framer-v-s06v3h",
    wnBX45izL: "framer-v-123tbpy"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "VM9yIq6SY",
    "Variant 2": "CaaLAiDVm",
    "Variant 3": "wnBX45izL"
};
const getProps = ({
    height,
    id,
    message,
    width,
    ...props
}) => {
    return { ...props,
        pcs_ZoWCD: message ? ? props.pcs_ZoWCD ? ? "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.We are looking forward to see you at the wedding.",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "VM9yIq6SY"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        pcs_ZoWCD,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "VM9yIq6SY",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-s06v3h", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "VM9yIq6SY",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        CaaLAiDVm: {
                            "data-framer-name": "Variant 2"
                        },
                        wnBX45izL: {
                            "data-framer-name": "Variant 3"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-vzvg8k",
                        layoutDependency: layoutDependency,
                        layoutId: "lbspS3noG",
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                        "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                        "--framer-font-size": "20px",
                                        "--framer-line-height": "1.3em",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(251, 237, 226))"
                                    },
                                    children: "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.We are looking forward to see you at the wedding."
                                })
                            }),
                            className: "framer-ijl5j3",
                            "data-framer-name": "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness. We are looking forward to see you at the wedding.",
                            fonts: ["GF;Yaldevi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "vbZIV0_3b",
                            style: {
                                "--extracted-r6o4lv": "rgb(251, 237, 226)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: pcs_ZoWCD,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-aHoRy.framer-og6in6, .framer-aHoRy .framer-og6in6 { display: block; }", ".framer-aHoRy.framer-s06v3h { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 600px; }", ".framer-aHoRy .framer-vzvg8k { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-aHoRy .framer-ijl5j3 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 156
 * @framerIntrinsicWidth 600
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"CaaLAiDVm":{"layout":["fixed","auto"]},"wnBX45izL":{"layout":["fixed","auto"]}}}
 * @framerVariables {"pcs_ZoWCD":"message"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerEwMieS7LX = withCSS(Component, css, "framer-aHoRy");
export default FramerEwMieS7LX;
FramerEwMieS7LX.displayName = "Couple's message";
FramerEwMieS7LX.defaultProps = {
    height: 156,
    width: 600
};
addPropertyControls(FramerEwMieS7LX, {
    variant: {
        options: ["VM9yIq6SY", "CaaLAiDVm", "wnBX45izL"],
        optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
        title: "Variant",
        type: ControlType.Enum
    },
    pcs_ZoWCD: {
        defaultValue: "We are both so delighted that you are able to join us in celebrating what we hope will be one of the happiest days of our lives. The affection shown to us by so many people since our roka has been incredibly moving, and has touched us both deeply. We would like to take this opportunity to thank everyone most sincerely for their kindness.We are looking forward to see you at the wedding.",
        description: "Write your custom couple's message above\n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Message",
        type: ControlType.String
    }
});
addFonts(FramerEwMieS7LX, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Yaldevi",
        source: "google",
        style: "normal",
        uiFamilyName: "Yaldevi",
        url: "https://fonts.gstatic.com/s/yaldevi/v17/cY9afj6VW0NMrDWtDNzCOwlPMq9SLpdxJzvtbxLCBJkS.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerEwMieS7LX",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "156",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"CaaLAiDVm\":{\"layout\":[\"fixed\",\"auto\"]},\"wnBX45izL\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerVariables": "{\"pcs_ZoWCD\":\"message\"}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "600",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./EwMieS7LX.map