// Generated by Framer (9805f18)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-8G8p9";
const variantClassNames = {
    zXAz0YHbd: "framer-v-1xvuffd"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    mantra,
    width,
    ...props
}) => {
    return { ...props,
        Ka1jTZQ18: mantra ? ? props.Ka1jTZQ18 ? ? "ॐ श्री गणेशाय नम"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Ka1jTZQ18,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "zXAz0YHbd",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1xvuffd", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "zXAz0YHbd",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-4ipfp3",
                        layoutDependency: layoutDependency,
                        layoutId: "OygGUnSD8",
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7R290dS1yZWd1bGFy",
                                        "--framer-font-family": '"Gotu", "Gotu Placeholder", sans-serif',
                                        "--framer-font-size": "15px",
                                        "--framer-line-height": "150%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                    },
                                    children: "ॐ श्री गणेशाय नम"
                                })
                            }),
                            className: "framer-q8es40",
                            "data-framer-name": "ॐ श्री गणेशाय नम",
                            fonts: ["GF;Gotu-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "YzQq0DDS8",
                            style: {
                                "--extracted-r6o4lv": "rgb(243, 236, 186)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: Ka1jTZQ18,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-8G8p9.framer-6eagri, .framer-8G8p9 .framer-6eagri { display: block; }", ".framer-8G8p9.framer-1xvuffd { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }", ".framer-8G8p9 .framer-4ipfp3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 124px; }", ".framer-8G8p9 .framer-q8es40 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 22.5
 * @framerIntrinsicWidth 124
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"Ka1jTZQ18":"mantra"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerYR50a2vE3 = withCSS(Component, css, "framer-8G8p9");
export default FramerYR50a2vE3;
FramerYR50a2vE3.displayName = "Mantra 2";
FramerYR50a2vE3.defaultProps = {
    height: 22.5,
    width: 124
};
addPropertyControls(FramerYR50a2vE3, {
    Ka1jTZQ18: {
        defaultValue: "ॐ श्री गणेशाय नम",
        description: "Enter your religious mantra above. \n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Mantra",
        type: ControlType.String
    }
});
addFonts(FramerYR50a2vE3, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Gotu",
        source: "google",
        style: "normal",
        uiFamilyName: "Gotu",
        url: "https://fonts.gstatic.com/s/gotu/v18/o-0FIpksx3QOlHgLioh6-hU.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerYR50a2vE3",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "22.5",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "124",
                "framerColorSyntax": "true",
                "framerVariables": "{\"Ka1jTZQ18\":\"mantra\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./YR50a2vE3.map