// Generated by Framer (0f6ce29)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getLoadingLazyAtYPosition,
    Image,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Slideshow from "https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/vzgdvq3ezmf3RWurtT17/SlideShow.js";
const SlideshowFonts = getFonts(Slideshow);
const cycleOrder = ["BVwCBy1TJ", "rJHfDYEwg"];
const serializationHash = "framer-PPAEO";
const variantClassNames = {
    BVwCBy1TJ: "framer-v-m9xna6",
    rJHfDYEwg: "framer-v-9swqiw"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Desktop: "BVwCBy1TJ",
    Phone: "rJHfDYEwg"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "BVwCBy1TJ"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "BVwCBy1TJ",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-m9xna6", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "BVwCBy1TJ",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        rJHfDYEwg: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1b8vhu9",
                        layoutDependency: layoutDependency,
                        layoutId: "lFYH8JeD2",
                        children: [ /*#__PURE__*/ _jsx(Image, {
                            background: {
                                alt: "",
                                fit: "fill",
                                intrinsicHeight: 379,
                                intrinsicWidth: 253,
                                loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 1035) - 0 - 1035.27) / 2) + 0),
                                pixelHeight: 758,
                                pixelWidth: 506,
                                sizes: "691.09px",
                                src: "https://framerusercontent.com/images/54JwjUrKR8txnFhN4dFmme3FzoQ.png?width=506&height=758",
                                srcSet: "https://framerusercontent.com/images/54JwjUrKR8txnFhN4dFmme3FzoQ.png?width=506&height=758 506w"
                            },
                            className: "framer-4rlk9i",
                            "data-framer-name": "The frame",
                            layoutDependency: layoutDependency,
                            layoutId: "zg_bCFKPn",
                            ...addPropertyOverrides({
                                rJHfDYEwg: {
                                    background: {
                                        alt: "",
                                        fit: "fill",
                                        intrinsicHeight: 379,
                                        intrinsicWidth: 253,
                                        loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 583.5) - 0 - 584.03) / 2) + 0),
                                        pixelHeight: 758,
                                        pixelWidth: 506,
                                        sizes: "389.87px",
                                        src: "https://framerusercontent.com/images/54JwjUrKR8txnFhN4dFmme3FzoQ.png?width=506&height=758",
                                        srcSet: "https://framerusercontent.com/images/54JwjUrKR8txnFhN4dFmme3FzoQ.png?width=506&height=758 506w"
                                    }
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1ozbtfd-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "xRuhSRQYV-container",
                                nodeId: "xRuhSRQYV",
                                rendersWithMotion: true,
                                scopeId: "a_Q6oz22n",
                                children: /*#__PURE__*/ _jsx(Slideshow, {
                                    alignment: "center",
                                    arrowOptions: {
                                        arrowFill: "rgba(0, 0, 0, 0.2)",
                                        arrowGap: 10,
                                        arrowPadding: 20,
                                        arrowPaddingBottom: 0,
                                        arrowPaddingLeft: 0,
                                        arrowPaddingRight: 0,
                                        arrowPaddingTop: 0,
                                        arrowPosition: "auto",
                                        arrowRadius: 40,
                                        arrowShouldFadeIn: false,
                                        arrowShouldSpace: true,
                                        arrowSize: 40,
                                        showMouseControls: false
                                    },
                                    autoPlayControl: true,
                                    borderRadius: 39,
                                    direction: "left",
                                    dragControl: false,
                                    effectsOptions: {
                                        effectsHover: true,
                                        effectsOpacity: 1,
                                        effectsPerspective: 1200,
                                        effectsRotate: 0,
                                        effectsScale: 1,
                                        playOffscreen: false
                                    },
                                    fadeOptions: {
                                        fadeAlpha: 0,
                                        fadeContent: false,
                                        fadeInset: 0,
                                        fadeWidth: 25,
                                        overflow: false
                                    },
                                    gap: 0,
                                    height: "100%",
                                    id: "xRuhSRQYV",
                                    intervalControl: 2,
                                    itemAmount: 1,
                                    layoutId: "xRuhSRQYV",
                                    padding: 0,
                                    paddingBottom: 0,
                                    paddingLeft: 0,
                                    paddingPerSide: false,
                                    paddingRight: 0,
                                    paddingTop: 0,
                                    progressOptions: {
                                        dotsActiveOpacity: 1,
                                        dotsBackground: "rgba(0, 0, 0, 0.2)",
                                        dotsBlur: 0,
                                        dotsFill: "rgb(255, 255, 255)",
                                        dotsGap: 7,
                                        dotsInset: 40,
                                        dotSize: 6,
                                        dotsOpacity: .5,
                                        dotsPadding: 3,
                                        dotsRadius: 165,
                                        showProgressDots: true
                                    },
                                    slots: [ /*#__PURE__*/ _jsx(Image, {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            src: "/framerusercontent.com/images/media__1781017365100.jpg"
                                        },
                                        className: "framer-679jd",
                                        "data-framer-name": "Wedding shoot 1",
                                        layoutDependency: layoutDependency,
                                        layoutId: "UTOcBWItA"
                                    }), /*#__PURE__*/ _jsx(Image, {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            src: "/framerusercontent.com/images/media__1781017365106.jpg"
                                        },
                                        className: "framer-sif4cl",
                                        "data-framer-name": "Wedding shoot 2",
                                        layoutDependency: layoutDependency,
                                        layoutId: "ym41tHEP9"
                                    }), /*#__PURE__*/ _jsx(Image, {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            src: "/framerusercontent.com/images/media__1781017365111.jpg"
                                        },
                                        className: "framer-1w6qfi3",
                                        "data-framer-name": "Wedding shoot 3",
                                        layoutDependency: layoutDependency,
                                        layoutId: "a2ZckpiNZ"
                                    }), /*#__PURE__*/ _jsx(Image, {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            src: "/framerusercontent.com/images/media__1781017365114.jpg"
                                        },
                                        className: "framer-1qvpcia",
                                        "data-framer-name": "Wedding shoot 4",
                                        layoutDependency: layoutDependency,
                                        layoutId: "UCPIHFPhp"
                                    }), /*#__PURE__*/ _jsx(Image, {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            src: "/framerusercontent.com/images/media__1781017365136.jpg"
                                        },
                                        className: "framer-pft7l8",
                                        "data-framer-name": "Wedding shoot 5",
                                        layoutDependency: layoutDependency,
                                        layoutId: "XU9cUQ2Ih"
                                    })],
                                    startFrom: 0,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    transitionControl: {
                                        damping: 40,
                                        delay: 0,
                                        mass: 1,
                                        stiffness: 200,
                                        type: "spring"
                                    },
                                    width: "100%"
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-PPAEO.framer-1l73s0b, .framer-PPAEO .framer-1l73s0b { display: block; }", ".framer-PPAEO.framer-m9xna6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 27.31px; height: 1035px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1016px; }", ".framer-PPAEO .framer-1b8vhu9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 27.31px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-PPAEO .framer-4rlk9i { aspect-ratio: 0.6675461741424802 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 1035px); overflow: visible; position: relative; width: 691px; z-index: 1; }", ".framer-PPAEO .framer-1ozbtfd-container { flex: none; height: 530px; left: calc(50.806451612903246% - 349.64px / 2); position: absolute; top: 382px; width: 350px; z-index: 0; }", ".framer-PPAEO .framer-679jd, .framer-PPAEO .framer-sif4cl, .framer-PPAEO .framer-1w6qfi3, .framer-PPAEO .framer-1qvpcia, .framer-PPAEO .framer-pft7l8, .framer-PPAEO .framer-l15e94 { aspect-ratio: 0.6666666666666666 / 1; height: var(--framer-aspect-ratio-supported, 402px); overflow: visible; position: relative; width: 268px; }", ".framer-PPAEO.framer-v-9swqiw.framer-m9xna6 { gap: 15.41px; height: 583px; width: 573px; }", ".framer-PPAEO.framer-v-9swqiw .framer-1b8vhu9 { gap: 15.41px; }", ".framer-PPAEO.framer-v-9swqiw .framer-4rlk9i { height: var(--framer-aspect-ratio-supported, 584px); width: 390px; }", ".framer-PPAEO.framer-v-9swqiw .framer-1ozbtfd-container { height: 299px; left: calc(50.806451612903246% - 197.25px / 2); top: 216px; width: 197px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1035
 * @framerIntrinsicWidth 1016
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"rJHfDYEwg":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framera_Q6oz22n = withCSS(Component, css, "framer-PPAEO");
export default Framera_Q6oz22n;
Framera_Q6oz22n.displayName = "Mirror";
Framera_Q6oz22n.defaultProps = {
    height: 1035,
    width: 1016
};
addPropertyControls(Framera_Q6oz22n, {
    variant: {
        options: ["BVwCBy1TJ", "rJHfDYEwg"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(Framera_Q6oz22n, [{
    explicitInter: true,
    fonts: []
}, ...SlideshowFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framera_Q6oz22n",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "1016",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"rJHfDYEwg\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicHeight": "1035",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./a_Q6oz22n.map