// Generated by Framer (3bd990b)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["bAmhJlmUV", "Q5T22NMeC"];
const serializationHash = "framer-ij9jz";
const variantClassNames = {
    bAmhJlmUV: "framer-v-ky7q6d",
    Q5T22NMeC: "framer-v-12zmt42"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const mkRqKd7Wh = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "bAmhJlmUV",
    Phone: "Q5T22NMeC"
};
const getProps = ({
    height,
    id,
    joinUs,
    width,
    ...props
}) => {
    return { ...props,
        mkRqKd7Wh: joinUs ? ? props.mkRqKd7Wh ? ? "You to join us in the wedding celebrations of",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "bAmhJlmUV"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        mkRqKd7Wh,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "bAmhJlmUV",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-ky7q6d", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "bAmhJlmUV",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        Q5T22NMeC: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                    "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                    "--framer-font-size": "30px",
                                    "--framer-letter-spacing": "-0.05em",
                                    "--framer-line-height": "100%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                },
                                children: "You to join us in the wedding celebrations of"
                            })
                        }),
                        className: "framer-1sgfkcc",
                        "data-framer-name": "You to join us in the wedding celebrations of",
                        fonts: ["GF;Cormorant Upright-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "OCLllGEAm",
                        style: {
                            "--extracted-r6o4lv": "rgb(243, 236, 186)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: mkRqKd7Wh,
                        transformTemplate: transformTemplate1,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            Q5T22NMeC: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50IFVwcmlnaHQtcmVndWxhcg==",
                                            "--framer-font-family": '"Cormorant Upright", "Cormorant Upright Placeholder", serif',
                                            "--framer-font-size": "20px",
                                            "--framer-letter-spacing": "-0.05em",
                                            "--framer-line-height": "100%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(243, 236, 186))"
                                        },
                                        children: "You to join us in the wedding celebrations of"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ij9jz.framer-wu595n, .framer-ij9jz .framer-wu595n { display: block; }", ".framer-ij9jz.framer-ky7q6d { height: 30px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 445px; }", ".framer-ij9jz .framer-1sgfkcc { flex: none; height: auto; left: 50%; position: absolute; top: 48%; white-space: pre-wrap; width: 445px; word-break: break-word; word-wrap: break-word; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 30
 * @framerIntrinsicWidth 445
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Q5T22NMeC":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"mkRqKd7Wh":"joinUs"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerQgMbyvyd3 = withCSS(Component, css, "framer-ij9jz");
export default FramerQgMbyvyd3;
FramerQgMbyvyd3.displayName = "Join us";
FramerQgMbyvyd3.defaultProps = {
    height: 30,
    width: 445
};
addPropertyControls(FramerQgMbyvyd3, {
    variant: {
        options: ["bAmhJlmUV", "Q5T22NMeC"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    mkRqKd7Wh: {
        defaultValue: "You to join us in the wedding celebrations of",
        description: "Press Shift + Enter to move to a new line",
        displayTextArea: true,
        title: "Join us",
        type: ControlType.String
    }
});
addFonts(FramerQgMbyvyd3, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Cormorant Upright",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant Upright",
        url: "https://fonts.gstatic.com/s/cormorantupright/v19/VuJrdM3I2Y35poFONtLdafkUCHw1y2vQjjTkeMnz.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerQgMbyvyd3",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "445",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Q5T22NMeC\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerVariables": "{\"mkRqKd7Wh\":\"joinUs\"}",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "30"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./QgMbyvyd3.map