// Generated by Framer (9805f18)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["RKg0uWW9B", "Qt4zKMLat"];
const serializationHash = "framer-VcSlJ";
const variantClassNames = {
    Qt4zKMLat: "framer-v-11ep14p",
    RKg0uWW9B: "framer-v-1ar8i4h"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "RKg0uWW9B",
    Phone: "Qt4zKMLat"
};
const getProps = ({
    height,
    icon,
    id,
    info,
    title,
    width,
    ...props
}) => {
    return { ...props,
        PrrSJxMUh: info ? ? props.PrrSJxMUh ? ? "While posting photos on social media please use the hashtag - #BadriKiDulhania",
        PVzPSjchM: title ? ? props.PVzPSjchM ? ? "Hashtag",
        RXLhSfcG1: icon ? ? props.RXLhSfcG1 ? ? {
            alt: "",
            pixelHeight: 1024,
            pixelWidth: 1024,
            src: "https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?scale-down-to=512&width=1024&height=1024",
            srcSet: "https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/WtUtKiZfYvFe6ob7yo3S6KaxT4.png?width=1024&height=1024 1024w"
        },
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "RKg0uWW9B"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        RXLhSfcG1,
        PVzPSjchM,
        PrrSJxMUh,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "RKg0uWW9B",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ar8i4h", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "RKg0uWW9B",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        Qt4zKMLat: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1x8nr7w",
                        layoutDependency: layoutDependency,
                        layoutId: "lmAiYM8JT",
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-f4gc8b",
                            layoutDependency: layoutDependency,
                            layoutId: "CRuVfnLh0",
                            children: /*#__PURE__*/ _jsx(Image, {
                                background: {
                                    alt: "",
                                    fit: "fit",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 182) - 0 - (Math.max(0, ((componentViewport ? .height || 182) - 0 - 0) / 1) * 1 + 0)) / 2 + 0 + 0) + 0 + ((Math.max(0, ((componentViewport ? .height || 182) - 0 - 0) / 1) * 1 - 0 - 351) / 2 + 0 + 0) + 0),
                                    sizes: "71px",
                                    ...toResponsiveImage(RXLhSfcG1),
                                    ...{
                                        positionX: "center",
                                        positionY: "center"
                                    }
                                },
                                className: "framer-1jzdh0c",
                                "data-framer-name": "ChatGPT Image Aug 20, 2025 at 02_43_47 PM 1",
                                layoutDependency: layoutDependency,
                                layoutId: "f_20N19BK",
                                ...addPropertyOverrides({
                                    Qt4zKMLat: {
                                        background: {
                                            alt: "",
                                            fit: "fit",
                                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 230) - 0 - (Math.max(0, ((componentViewport ? .height || 230) - 0 - 0) / 1) * 1 + 0)) / 2 + 0 + 0) + 0 + ((Math.max(0, ((componentViewport ? .height || 230) - 0 - 0) / 1) * 1 - 0 - 480.57) / 2 + 0 + 0) + 0),
                                            sizes: "118.57px",
                                            ...toResponsiveImage(RXLhSfcG1),
                                            ...{
                                                positionX: "center",
                                                positionY: "center"
                                            }
                                        }
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                        "--framer-font-family": '"Aboreto", sans-serif',
                                        "--framer-font-size": "32px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                    },
                                    children: "Hashtag"
                                })
                            }),
                            className: "framer-v0c8nb",
                            "data-framer-name": "Hashtag",
                            fonts: ["GF;Aboreto-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "Cu8fitgsS",
                            style: {
                                "--extracted-r6o4lv": "rgb(105, 107, 54)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: PVzPSjchM,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                Qt4zKMLat: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                                "--framer-font-family": '"Aboreto", sans-serif',
                                                "--framer-font-size": "40px",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                            },
                                            children: "Hashtag"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                        "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                        "--framer-font-size": "12px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                    },
                                    children: "While posting photos on social media please use the hashtag - #BadriKiDulhania"
                                })
                            }),
                            className: "framer-1ilsgfh",
                            "data-framer-name": "#BadriKiDulhania",
                            fonts: ["GF;Yaldevi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "nvwjswqlQ",
                            style: {
                                "--extracted-r6o4lv": "rgb(105, 107, 54)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: PrrSJxMUh,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                Qt4zKMLat: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                                "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                                "--framer-font-size": "15px",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(105, 107, 54))"
                                            },
                                            children: "While posting photos on social media please use the hashtag - #BadriKiDulhania"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-VcSlJ.framer-1beh0t3, .framer-VcSlJ .framer-1beh0t3 { display: block; }", ".framer-VcSlJ.framer-1ar8i4h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 182px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 188px; }", ".framer-VcSlJ .framer-1x8nr7w { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 1px; justify-content: center; max-width: 200px; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-VcSlJ .framer-f4gc8b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-VcSlJ .framer-1jzdh0c { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 71px); position: relative; width: 71px; }", ".framer-VcSlJ .framer-v0c8nb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 234px; word-break: break-word; word-wrap: break-word; }", ".framer-VcSlJ .framer-1ilsgfh { flex: none; height: auto; max-width: 150%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-VcSlJ.framer-v-11ep14p.framer-1ar8i4h { height: 230px; width: 327px; }", ".framer-VcSlJ.framer-v-11ep14p .framer-1x8nr7w { gap: 16px; }", ".framer-VcSlJ.framer-v-11ep14p .framer-1jzdh0c { height: var(--framer-aspect-ratio-supported, 119px); width: 119px; }", ".framer-VcSlJ.framer-v-11ep14p .framer-v0c8nb { width: 327px; }", ".framer-VcSlJ.framer-v-11ep14p .framer-1ilsgfh { max-width: 100%; width: 327px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 182
 * @framerIntrinsicWidth 188
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Qt4zKMLat":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"RXLhSfcG1":"icon","PVzPSjchM":"title","PrrSJxMUh":"info"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerOsVK1nfP_ = withCSS(Component, css, "framer-VcSlJ");
export default FramerOsVK1nfP_;
FramerOsVK1nfP_.displayName = "Thing to know - Info";
FramerOsVK1nfP_.defaultProps = {
    height: 182,
    width: 188
};
addPropertyControls(FramerOsVK1nfP_, {
    variant: {
        options: ["RKg0uWW9B", "Qt4zKMLat"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    RXLhSfcG1: {
        __defaultAssetReference: "data:framer/asset-reference,WtUtKiZfYvFe6ob7yo3S6KaxT4.png?originalFilename=ChatGPT+Image+Aug+20%2C+2025+at+02_43_47+PM+1.png&preferredSize=auto",
        __vekterDefault: {
            alt: "",
            assetReference: "data:framer/asset-reference,WtUtKiZfYvFe6ob7yo3S6KaxT4.png?originalFilename=ChatGPT+Image+Aug+20%2C+2025+at+02_43_47+PM+1.png&preferredSize=auto"
        },
        title: "Icon",
        type: ControlType.ResponsiveImage
    },
    PVzPSjchM: {
        defaultValue: "Hashtag",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    PrrSJxMUh: {
        defaultValue: "While posting photos on social media please use the hashtag - #BadriKiDulhania",
        description: "Find more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Info",
        type: ControlType.String
    }
});
addFonts(FramerOsVK1nfP_, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Aboreto",
        source: "google",
        style: "normal",
        uiFamilyName: "Aboreto",
        url: "https://fonts.gstatic.com/s/aboreto/v2/5DCXAKLhwDDQ4N8blKHeA2yuxSY.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Yaldevi",
        source: "google",
        style: "normal",
        uiFamilyName: "Yaldevi",
        url: "https://fonts.gstatic.com/s/yaldevi/v17/cY9afj6VW0NMrDWtDNzCOwlPMq9SLpdxJzvtbxLCBJkS.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerOsVK1nfP_",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Qt4zKMLat\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerVariables": "{\"RXLhSfcG1\":\"icon\",\"PVzPSjchM\":\"title\",\"PrrSJxMUh\":\"info\"}",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "182",
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "188",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./OsVK1nfP_.map