// Generated by Framer (4076eae)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["kDcaosY36", "rlzkd_xq1"];
const serializationHash = "framer-Lszbe";
const variantClassNames = {
    kDcaosY36: "framer-v-1jww7zj",
    rlzkd_xq1: "framer-v-2nkfo4"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "kDcaosY36",
    Phone: "rlzkd_xq1"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "kDcaosY36"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "kDcaosY36",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1jww7zj", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "kDcaosY36",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        rlzkd_xq1: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1qcl0cs",
                        "data-framer-name": "CTA - 1",
                        layoutDependency: layoutDependency,
                        layoutId: "YCQeC3R0k",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsxs(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                        "--framer-font-family": '"Aboreto", sans-serif',
                                        "--framer-font-size": "70px",
                                        "--framer-line-height": "115.74%",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(251, 237, 226))"
                                    },
                                    children: "Contact"
                                })
                            }),
                            className: "framer-gkvj1z",
                            "data-framer-name": "join our journey",
                            fonts: ["GF;Aboreto-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "uHBXTG1tr",
                            style: {
                                "--extracted-r6o4lv": "rgb(251, 237, 226)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                rlzkd_xq1: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsxs(motion.p, {
                                            style: {
                                                "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                                "--framer-font-family": '"Aboreto", sans-serif',
                                                "--framer-font-size": "50px",
                                                "--framer-line-height": "115.74%",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(251, 237, 226))"
                                            },
                                            children: /*#__PURE__*/ _jsx(motion.span, {
                                                style: {
                                                    "--framer-font-size": "70px"
                                                },
                                                children: "Contact"
                                            })
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                        "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                        "--framer-font-size": "20px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(251, 237, 226))"
                                    },
                                    children: "Click to message on WhatsApp"
                                })
                            }),
                            className: "framer-1oxcjh8",
                            "data-framer-name": "Click to open the map",
                            fonts: ["GF;Yaldevi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "iSB36kAwL",
                            style: {
                                "--extracted-r6o4lv": "rgb(251, 237, 226)",
                                "--framer-paragraph-spacing": "0px"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Lszbe.framer-g5s2lp, .framer-Lszbe .framer-g5s2lp { display: block; }", ".framer-Lszbe.framer-1jww7zj { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }", ".framer-Lszbe .framer-1qcl0cs { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 50px 0px 30px 0px; position: relative; width: 100%; }", ".framer-Lszbe .framer-gkvj1z, .framer-Lszbe .framer-1oxcjh8 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 479px; word-break: break-word; word-wrap: break-word; }", ".framer-Lszbe.framer-v-2nkfo4 .framer-1qcl0cs { order: 0; padding: 71px 0px 30px 0px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 301
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"rlzkd_xq1":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerbMSELzOfJ = withCSS(Component, css, "framer-Lszbe");
export default FramerbMSELzOfJ;
FramerbMSELzOfJ.displayName = "CTA - 2";
FramerbMSELzOfJ.defaultProps = {
    height: 301,
    width: 1200
};
addPropertyControls(FramerbMSELzOfJ, {
    variant: {
        options: ["kDcaosY36", "rlzkd_xq1"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerbMSELzOfJ, [{
    explicitInter: true,
    fonts: [{
        family: "Aboreto",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/aboreto/v2/5DCXAKLhwDDQ4N8blKHeA2yuxSY.woff2",
        weight: "400"
    }, {
        family: "Yaldevi",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/yaldevi/v17/cY9afj6VW0NMrDWtDNzCOwlPMq9SLpdxJzvtbxLCBJkS.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerbMSELzOfJ",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "1200",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"rlzkd_xq1\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "301"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./bMSELzOfJ.map