// Generated by Framer (04b9457)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["lr8le1kO5", "XUwHzQMHS"];
const serializationHash = "framer-37b6A";
const variantClassNames = {
    lr8le1kO5: "framer-v-1x9ovf3",
    XUwHzQMHS: "framer-v-1w5tm9c"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "lr8le1kO5",
    Phone: "XUwHzQMHS"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "lr8le1kO5"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "lr8le1kO5",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1x9ovf3", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "lr8le1kO5",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        XUwHzQMHS: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                    "--framer-font-family": '"Aboreto", sans-serif',
                                    "--framer-font-size": "70px",
                                    "--framer-line-height": "115.74%",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(220, 221, 166))"
                                },
                                children: "See the route"
                            })
                        }),
                        className: "framer-78j2p3",
                        "data-framer-name": "join our journey",
                        fonts: ["GF;Aboreto-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "jrTe71hyy",
                        style: {
                            "--extracted-r6o4lv": "rgb(220, 221, 166)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            XUwHzQMHS: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7QWJvcmV0by1yZWd1bGFy",
                                            "--framer-font-family": '"Aboreto", sans-serif',
                                            "--framer-font-size": "50px",
                                            "--framer-line-height": "115.74%",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(220, 221, 166))"
                                        },
                                        children: "See the route"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7WWFsZGV2aS1yZWd1bGFy",
                                    "--framer-font-family": '"Yaldevi", "Yaldevi Placeholder", sans-serif',
                                    "--framer-font-size": "20px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(218, 220, 163))"
                                },
                                children: "Click to open the map"
                            })
                        }),
                        className: "framer-131sa28",
                        "data-framer-name": "Click to open the map",
                        fonts: ["GF;Yaldevi-regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "iuAm2eBDS",
                        style: {
                            "--extracted-r6o4lv": "rgb(218, 220, 163)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-37b6A.framer-10xdu6d, .framer-37b6A .framer-10xdu6d { display: block; }", ".framer-37b6A.framer-1x9ovf3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 17px 0px 30px 0px; position: relative; width: 1200px; }", ".framer-37b6A .framer-78j2p3, .framer-37b6A .framer-131sa28 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 479px; word-break: break-word; word-wrap: break-word; }", ".framer-37b6A.framer-v-1w5tm9c.framer-1x9ovf3 { padding: 200px 0px 44px 0px; }", ".framer-37b6A.framer-v-1w5tm9c .framer-78j2p3 { width: 357px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 268
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"XUwHzQMHS":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerLaZ7mwlwJ = withCSS(Component, css, "framer-37b6A");
export default FramerLaZ7mwlwJ;
FramerLaZ7mwlwJ.displayName = "CTA - 1";
FramerLaZ7mwlwJ.defaultProps = {
    height: 268,
    width: 1200
};
addPropertyControls(FramerLaZ7mwlwJ, {
    variant: {
        options: ["lr8le1kO5", "XUwHzQMHS"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerLaZ7mwlwJ, [{
    explicitInter: true,
    fonts: [{
        family: "Aboreto",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/aboreto/v2/5DCXAKLhwDDQ4N8blKHeA2yuxSY.woff2",
        weight: "400"
    }, {
        family: "Yaldevi",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/yaldevi/v17/cY9afj6VW0NMrDWtDNzCOwlPMq9SLpdxJzvtbxLCBJkS.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerLaZ7mwlwJ",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "268",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "1200",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"XUwHzQMHS\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./LaZ7mwlwJ.map