// Generated by Framer (0f6ce29)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX,
    withOptimizedAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/xIdCWBJkwffV9con21b4/o2wRdstCLxPneFPX0Dki/BlJD2usrt.js";
const RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(RichText));
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["myVzBj9_9", "Gu5N1YQEk", "LyDtq4bSL"];
const serializationHash = "framer-xrlcc";
const variantClassNames = {
    Gu5N1YQEk: "framer-v-a9kwxn",
    LyDtq4bSL: "framer-v-5lazgu",
    myVzBj9_9: "framer-v-29qkbk"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const q_Mw9gntU = undefined;
const BGQVPX9uc = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const transition2 = {
    bounce: .2,
    delay: 0,
    duration: 5.2,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition2,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: 1,
    rotate: 12,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 400
};
const animation2 = {
    opacity: 1,
    rotate: 15,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 400
};
const animation3 = {
    opacity: 1,
    rotate: -10,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 400
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Desktop: "myVzBj9_9",
    Phone: "LyDtq4bSL",
    Tablet: "Gu5N1YQEk"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    name1,
    name2,
    width,
    ...props
}) => {
    return { ...props,
        BGQVPX9uc: name2 ? ? props.BGQVPX9uc ? ? "KANIKA",
        q_Mw9gntU: name1 ? ? props.q_Mw9gntU ? ? "ABHISHEK",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "myVzBj9_9"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        q_Mw9gntU,
        BGQVPX9uc,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "myVzBj9_9",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(MotionDivWithFX, { ...restProps,
                    ...gestureHandlers,
                    __framer__adjustPosition: false,
                    __framer__offset: 0,
                    __framer__parallaxTransformEnabled: true,
                    __framer__speed: 70,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: cx(scopingClassNames, "framer-29qkbk", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "myVzBj9_9",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        Gu5N1YQEk: {
                            "data-framer-name": "Tablet"
                        },
                        LyDtq4bSL: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
                        __fromCanvasComponent: true,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        animate: animation,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h3, {
                                className: "framer-styles-preset-1beymaa",
                                "data-styles-preset": "BlJD2usrt",
                                children: "ABHISHEK"
                            })
                        }),
                        className: "framer-t7d3wo",
                        "data-framer-appear-id": "t7d3wo",
                        fonts: ["Inter"],
                        initial: animation1,
                        layoutDependency: layoutDependency,
                        layoutId: "mKrJf6gU2",
                        optimized: true,
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: q_Mw9gntU,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
                        __fromCanvasComponent: true,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        animate: animation,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h2, {
                                dir: "auto",
                                style: {
                                    "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                    "--framer-font-family": '"Cormorant", "Cormorant Placeholder", serif',
                                    "--framer-font-size": "42px",
                                    "--framer-letter-spacing": "0.42em",
                                    "--framer-line-height": "60px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-1of0zx5, rgb(255, 253, 235))"
                                },
                                children: "WEDS"
                            })
                        }),
                        className: "framer-1p5h4t7",
                        "data-framer-appear-id": "1p5h4t7",
                        fonts: ["GF;Cormorant-regular"],
                        initial: animation2,
                        layoutDependency: layoutDependency,
                        layoutId: "xO9tu9JFu",
                        optimized: true,
                        style: {
                            "--extracted-1of0zx5": "rgb(255, 253, 235)",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            LyDtq4bSL: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.h2, {
                                        dir: "auto",
                                        style: {
                                            "--font-selector": "R0Y7Q29ybW9yYW50LXJlZ3VsYXI=",
                                            "--framer-font-family": '"Cormorant", "Cormorant Placeholder", serif',
                                            "--framer-font-size": "25px",
                                            "--framer-letter-spacing": "0.42em",
                                            "--framer-line-height": "27px",
                                            "--framer-text-alignment": "center",
                                            "--framer-text-color": "var(--extracted-1of0zx5, rgb(255, 253, 235))"
                                        },
                                        children: "WEDS"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichTextWithFXWithOptimizedAppearEffect, {
                        __fromCanvasComponent: true,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        animate: animation,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h3, {
                                className: "framer-styles-preset-1beymaa",
                                "data-styles-preset": "BlJD2usrt",
                                children: "KANIKA"
                            })
                        }),
                        className: "framer-11b7scn",
                        "data-framer-appear-id": "11b7scn",
                        fonts: ["Inter"],
                        initial: animation3,
                        layoutDependency: layoutDependency,
                        layoutId: "qk3x55j68",
                        optimized: true,
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: BGQVPX9uc,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-xrlcc.framer-9czprn, .framer-xrlcc .framer-9czprn { display: block; }", ".framer-xrlcc.framer-29qkbk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 393px; }", ".framer-xrlcc .framer-t7d3wo, .framer-xrlcc .framer-1p5h4t7, .framer-xrlcc .framer-11b7scn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-xrlcc.framer-v-5lazgu.framer-29qkbk { gap: 0px; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 393
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Gu5N1YQEk":{"layout":["fixed","auto"]},"LyDtq4bSL":{"layout":["fixed","auto"]}}}
 * @framerVariables {"q_Mw9gntU":"name1","BGQVPX9uc":"name2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerykp_6Qqjq = withCSS(Component, css, "framer-xrlcc");
export default Framerykp_6Qqjq;
Framerykp_6Qqjq.displayName = "Couple's names";
Framerykp_6Qqjq.defaultProps = {
    height: 200,
    width: 393
};
addPropertyControls(Framerykp_6Qqjq, {
    variant: {
        options: ["myVzBj9_9", "Gu5N1YQEk", "LyDtq4bSL"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    q_Mw9gntU: {
        defaultValue: "ABHISHEK",
        description: "Enter groom or bride's name above. \n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Name 1",
        type: ControlType.String
    },
    BGQVPX9uc: {
        defaultValue: "KANIKA",
        description: "Enter groom or bride's name above. \n\nFind more templates on missingpieceinvites.com",
        displayTextArea: true,
        title: "Name 2",
        type: ControlType.String
    }
});
addFonts(Framerykp_6Qqjq, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Cormorant",
        source: "google",
        style: "normal",
        uiFamilyName: "Cormorant",
        url: "https://fonts.gstatic.com/s/cormorant/v24/H4c2BXOCl9bbnla_nHIA47NMUjsNbCVrFhFTQ7Fg7A2uwYs.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerykp_6Qqjq",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "200",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"Gu5N1YQEk\":{\"layout\":[\"fixed\",\"auto\"]},\"LyDtq4bSL\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerVariables": "{\"q_Mw9gntU\":\"name1\",\"BGQVPX9uc\":\"name2\"}",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "393",
                "framerContractVersion": "1",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}